
BEGIN;

DROP TABLE IF EXISTS "level",
"answer",
"user",
"quiz",
"question",
"tag",
"quiz_has_tag";

-- -----------------------------------------------------
-- "level"
-- -----------------------------------------------------
CREATE TABLE "level" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "name" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  "updated_at" TIMESTAMPTZ
);

-----------------------------------------------------
-- "answer"
-- -----------------------------------------------------
CREATE TABLE "answer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" TEXT NOT NULL,
  "question_id" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-----------------------------------------------------
-- "app_user"
-- -----------------------------------------------------
CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "firstname" TEXT NULL,
  "lastname" TEXT NULL,
  "role" TEXT NOT NULL DEFAULT 'member',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
-- "quiz"
-- -----------------------------------------------------
CREATE TABLE "quiz" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "description" TEXT NULL,
  "author_id" INTEGER NOT NULL REFERENCES "user"("id"), -- Quiz author
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
--  "question"
-- -----------------------------------------------------
CREATE TABLE "question" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" TEXT NOT NULL,
  "anecdote" TEXT NULL,
  "wiki" TEXT NULL,
  "level_id" INTEGER NOT NULL REFERENCES "level"("id"),
  "answer_id" INTEGER NOT NULL REFERENCES "answer"("id"), -- 'The good answer for this.quizz'
  "quiz_id" INTEGER NOT NULL REFERENCES "quiz"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
--  "tag"
-- -----------------------------------------------------
CREATE TABLE "tag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-- -----------------------------------------------------
--  "quiz_has_tag"
-- -----------------------------------------------------
CREATE TABLE "quiz_has_tag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quiz_id" INTEGER NOT NULL REFERENCES "quiz"("id"),
  "tag_id" INTEGER NOT NULL REFERENCES "tag"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ,
  UNIQUE ("quiz_id", "tag_id")
);

ALTER TABLE "answer" ADD FOREIGN KEY ("question_id") REFERENCES "question"("id");


COMMIT;
